name: Deploy to Firebase

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Authenticate with Firebase
        run: firebase login:ci --token "$FIREBASE_TOKEN"
  
      - name: Deploy to Firebase
        run: firebase deploy --only hosting





